# Generated by Django 2.0.5 on 2018-08-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KMA_Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_hist1', models.CharField(max_length=100)),
                ('present_hist2', models.CharField(max_length=100)),
                ('present_hist3', models.CharField(max_length=100)),
                ('past_hist1', models.CharField(max_length=100)),
                ('past_hist2', models.CharField(max_length=100)),
                ('past_hist3', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KMA_Clinic.KMA')),
            ],
        ),
    ]
