# Generated by Django 2.0.5 on 2018-08-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KMA_Clinic', '0004_auto_20180803_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='past_hist1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visits',
            name='past_hist2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visits',
            name='past_hist3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visits',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KMA_Clinic.KMA'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='present_hist1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visits',
            name='present_hist2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visits',
            name='present_hist3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
