# Generated by Django 2.0.5 on 2018-08-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KMA_Clinic', '0005_auto_20180803_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kma',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kma',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kma',
            name='birthdate',
            field=models.DateTimeField(blank=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='kma',
            name='husband',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kma',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='visits',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KMA_Clinic.KMA'),
        ),
    ]
