# Generated by Django 2.0.5 on 2018-08-04 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KMA_Clinic', '0009_auto_20180804_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kma',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visits',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KMA_Clinic.KMA'),
        ),
    ]
